### PR TITLE
feat: `schematic_net_label.symbol_name`

### PR DESCRIPTION
**Pull request by Abse2001**
created fn to create symbols using schematic_net_label.symbol_name
hard-coding "ground_horz" as symbol_name for now until I finish the core side

### CODE REVIEW

**Review by seveibar — COMMENTED** [review]
Is there a way to avoid repeating so much code? Creating utility functions maybe?

**Comment by seveibar** [comment]
It’s copied from the other symbol rendering code right? Can we put it into shared functions in a clean way?

**Review by seveibar — APPROVED** [review]
With the snapshot testing im not too worried about refactoring later i suppose

**Comment by Abse2001** [comment]
@seveibar I tried to use the function that draw symbols but it take s schematic component not schematic label then I tried to convert the schematic net label to a schematic component but I ran to a problem it always say could not match ports,
if you now how to fix that I could use it

**Comment by Abse2001** [comment]
Putting it into a shared function sounds good too

**Comment by seveibar** [comment]
Lets do it in a future pr sinxe this is blocking @Abse2001

**Pull request merged**
